// Generated by CoffeeScript 1.10.0
(function() {
  var comment, initHandler, render_item, render_list;

  render_item = function(item) {
    var author_avatar, author_name, output_item, output_item_author;
    if (item.meta && item.meta.author_name) {
      author_avatar = item.meta.author_avatar || default_avatar;
      author_name = item.meta.author_name;
      output_item_author = '<img src="' + author_avatar + '" alt="' + author_name + '"/> <h5>' + author_name + '</h5>';
    } else {
      output_item_author = '<h5>' + _('Anonymous') + '</h5>';
    }
    output_item = '<div class="comm-item"> <div class="author-container">' + output_item_author + '</div> <div class="comm-container"> <p>' + item.content + '</p> </div> </div>';
    return output_item;
  };

  render_list = function(author, comm_items) {
    var i, item, len, output, output_author, output_comm_items;
    if (author) {
      output_author = '<img src="' + (author.avatar || default_avatar) + '" alt="' + author.name + '"/> <h5>' + author.name + '</h5>';
    } else {
      output_author = '<h5>' + _('Anonymous') + '</h5>';
    }
    output_comm_items = '';
    for (i = 0, len = comm_items.length; i < len; i++) {
      item = comm_items[i];
      output_comm_items += render_item(item);
    }
    return output = '<header> <h3>' + _('Comments:') + '</h3> </header> <form name="sup-exts-comment-form" class="comm-form"> <div class="author-container">' + output_author + '</div> <div class="input-container"> <div> <textarea placeholder="' + _('Your Comment here...') + '" rows="6"></textarea> </div> <button type="submit">' + _('Write your Comment') + '</button> </div> </form> <hr> <div class="comm-list">' + output_comm_items + '</div>';
  };

  if (typeof SupExtComment !== 'function') {
    throw 'SupExtComment not fully loaded!!';
  }

  comment = new SupExtComment();

  initHandler = function() {
    var comm_element, group_key;
    comm_element = document.querySelector('#sup-comment-exts-plugin');
    if (!comm_element) {
      return;
    }
    group_key = comm_element.getAttribute('group-key') || location.href;
    comment.query({
      key: group_key
    }).then(function(comments) {
      return comm_element.innerHTML = render_list(comment.author.profile, comments);
    })["catch"](function(error) {
      return console.log(error);
    });
  };

  document.addEventListener('DOMContentLoaded', initHandler);

}).call(this);
